### ISSUE TITLE
CMD_PORTAMENTODOWN can get out of bounds

### ISSUE THREAD

**Issue by Teteros** [sm-Fifteen/SteamControllerTracker#22]
Demo: https://streamable.com/052tk

```
Channel #0:F#4\\(-48/16)
Channel #0:F#4\\(-96/16)
Channel #0:F#4\\(-144/16)
Channel #0:F#4\\(-192/16)
Channel #0:F#4\\(-240/16)
Channel #0:F#4\\(-288/16)
Channel #0:F#4\\(-336/16)
Channel #0:F#4\\(-384/16)
Channel #0:F#4\\(-432/16)
Channel #0:F#4\\(-480/16)
Channel #0:F#4\\(-528/16)
Channel #0:F#4\\(-576/16)
Channel #0:F#4\\(-624/16)
Channel #0:F#4\\(-672/16)
Channel #0:F#4\\(-720/16)
Channel #0:F#4\\(-768/16)
Channel #0:F#4\\(-816/16)
Channel #0:F#4\\(-864/16)
Channel #0:F#4\\(-912/16)
Channel #0:F#4\\(-960/16)
Channel #0:F#4\\(-1008/16)
Channel #0:F#4\\(-1056/16)
Channel #0:F#4\\(-1104/16)
Unhandled rejection TypeError: "value" argument is out of bounds
    at checkInt (buffer.js:1178:11)
    at Buffer.writeUInt16LE (buffer.js:1236:5)
    at FeedbackPacket.generateBlob (SteamControllerTracker/node_modules/steam-controller-player/sc_packets.js:24:19)
    at SteamControllerTracker/node_modules/steam-controller-player/sc_device.js:54:40
    at tryCatcher (SteamControllerTracker/node_modules/bluebird/js/release/util.js:16:23)
    at Object.gotValue (SteamControllerTracker/node_modules/bluebird/js/release/reduce.js:155:18)
    at Object.gotAccum (SteamControllerTracker/node_modules/bluebird/js/release/reduce.js:144:25)
    at Object.tryCatcher (SteamControllerTracker/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (SteamControllerTracker/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (SteamControllerTracker/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromiseCtx (SteamControllerTracker/node_modules/bluebird/js/release/promise.js:606:10)
    at Async._drainQueue (SteamControllerTracker/node_modules/bluebird/js/release/async.js:138:12)
    at Async._drainQueues (SteamControllerTracker/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (SteamControllerTracker/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
```

The [original](https://www.youtube.com/watch?v=DlHG-gckal4) ChainChip doesn't play well on SC because speed/tempo/patternbreak effects were used a lot. I adjusted the base speed/tempo so it plays for the most part in `ChainChipSC.it`. Though had to record part 2 from pattern 81 (i.e `-s 80` in SteamControllerTracker)

Both original and edit are in the zip below.

[ChainChipV1.53.zip](https://github.com/sm-Fifteen/SteamControllerTracker/files/1219296/ChainChipV1.53.zip)

Play from pattern 80 with `node play_mod.js -c 1 -s 79 ChainChipSC.it`

Still need to track down what causes the `NaN`'s in that module. In https://youtu.be/fyv-gNpaVuw?t=5m42s they just sound like clicks.

**Comment by sm-Fifteen** [comment]
Looks like I don't reset the portamento effect when the same note is played again, so instead of 8 short slides, it tries to play a single really long one. That being said, going out of bounds is a possible case scenario for pretty much the tracker as a whole, so I'll see if I can't try and make it array-proof.
